### ISSUE TITLE
Session module methods cannot be found after changes of namespace to Api::V1

### ISSUE THREAD

**Issue by alvinvoo** [data-upstream/data-upstream-service-201902#3]
---
name: Session module methods cannot be found
about: After changes of namespace to Api::VI

---

**Describe the bug**
After changes of namespace to Api::VI, user can be created and login but any action that requires user token to be verified will throw error:

"status": 500,
    "error": "Internal Server Error",
    "exception": "#<NoMethodError: undefined method `require_read_write_user_access_token' for #<Api::V1::Users::StreamsController:0xe42ded4>>",

**To Reproduce**
1. Using Postman, with base url : localhost:3000/api/v1
2. Create a user locally with POST /users.json
3. Or login with existing user with POST /users/access_token.json
4. Tries to GET stream /users/streams.json or GET profile /profile
5. See error

**Screenshots** (click to enlarge)
![image](https://user-images.githubusercontent.com/28261161/52529652-a156a100-2d30-11e9-8f8d-f47c5514ce28.png)

**Device detail
 (please complete the following information):**
 - OS: 
Xbuntu 18.04
-  Java: 
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**Additional context**
Suspect is due to changes in namespace but Sessions module was not updated to reflect the correct namespace, hence methods could not be found.

**Comment by data-upstream** [comment]
Yes, this must get fixed as well. I was not there, yet. I thought you had this on the login. Could we include the sessions module as well?

**Comment by data-upstream** [comment]
module Api::V1::Concerns::Sessions
  extend ActiveSupport::Concern

in any others:
iclude Api::V1::Concerns::Sessions
