### ISSUE TITLE
Chrome  blocking due to CORS policy violation

### ISSUE THREAD

**Issue by alvinvoo** [data-upstream/data-upstream-service-201902#4]
---
name: Frontend is blocked from receiving request due to CORS policy violation
about: Rails need to specify CORS policy rules

---

**Describe the bug**
CORS policy issue with either Rails or Chrome

I see that Alex has installed rack-cors and written the cors.rb following the steps here:

![image](https://user-images.githubusercontent.com/28261161/52529914-5dff3100-2d36-11e9-90a9-ffe2bae9fe8d.png)

Either this doesn't work for Rails 5 or the issue exists in the Angular client side.

**Screenshots** (click to enlarge)

![image](https://user-images.githubusercontent.com/28261161/52529918-69eaf300-2d36-11e9-9a2c-17daf1b60dfe.png)

**Comment by yihangho** [comment]
The error message explains it all. We have two options here -- make sure the server returns the specific origin that it accepts (in this case, `http://localhost:4200`) or ensure that the credentials mode is not `include`.

The [previous version](https://github.com/data-upstream/data-upstream-service/blob/3bebb8c4fdc57d80e34bb139aab99c1db61734e7/config/application.rb#L33-L40) has already handled the first case. At the same time, using the second case is easy, too, by setting `withCredentials` to `false` [here](https://gitlab.com/afitterling/data-upstream-frontend/blob/02c79a51a57d8335453e6b29da1940110a5d3230/src/app/services/api/api.service.ts#L67).

@afitterling please advice how do you want to proceed with this.

**Comment by data-upstream** [comment]
@yihangho It seems you not having the latest code. It is all in the code, since beginning. However It does not work. You can check the Gemfile easily. Also you see it in initializers/cors.
The bug is not cors. The bug is we initialize cors and it does not work.

**Comment by data-upstream** [comment]
config/initializers/cors.rb (since beginning)

**Comment by data-upstream** [comment]
also of course I added it to application, however it did not work as well.

**Comment by data-upstream** [comment]
could you try?

**Comment by data-upstream** [comment]
Yihang, cors is already being setup in config/initializers/cors.rb 
So I applied the patch to the frontend, as it was the frontend. What implication does it have?

**Comment by yihangho** [comment]
No, the setup isn't the same as the old code. In the new code, the origin is hard-coded to `'*'`, which causes the problem. In the old code, a specific origin is provided based on the value of `ENV["PERMITTED_ORIGIN"]`.

**Comment by data-upstream** [comment]
yes, of course I know. the wildcard for dev environment however should work. also setting the host specifc does not work.

**Comment by data-upstream** [comment]
@Yihang, the app fix does not work either, it keeps redirecting. Is there an easy fix with the current rails setup (using wildcard)?

**Comment by yihangho** [comment]
In addition to setting the host, we also need to set `credentials: true`. The full fix looks like this:

```ruby
# config/initializers/cors.rb

Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    origins 'http://localhost:4200'

    resource '*',
      headers: :any,
      methods: [:get, :post, :options],
      credentials: true
  end
end
```

Obviously, we don't want to hard code the value of the origin here. I still stand by what I recommended (and did) in the past, which is to inject this value by an environment variable. I don't think this is a big deal as this value is not something that changes frequently in practice (e.g., when doing development, it's almost always `localhost:4200`).

To explain why wildcard used to work and why `credentials: true` was not needed previous, the `rack-cors` library has changed its behavior between the time we installed in the old code base and now. Previously, `rack-cors` automatically replaces the `'*'` origin with the actual origin that it sees. It doesn't do this anymore, that is, if we specify `'*'`, it will set that as the `Access-Control-Allow-Origin` header with it verbatim. Also, the value of `credentials` used to default to `true` but now defaults to `false`.

On a related note, I think issues like this should have been caught during the upgrade process. I am not sure how you did it, but any major upgrade (like this) should have been done piecewise in baby steps. Each step should be followed by rigorous testing to isolate any issues to a single cause.

**Comment by data-upstream** [comment]
Yihang. you were right, wildcard works not anymore. we set it statically and use env in production. The profile cannot be loaded currently, this is due the to included session module. very good.

**Comment by data-upstream** [comment]
fixed
