### ISSUE TITLE
Unauthorized error for /log_data.json endpoint

### ISSUE THREAD

**Issue by alvinvoo** [data-upstream/data-upstream-service-201902#8]
---
name: Accessing /log_data.json gives 401
about: This is an existing issue even in https://alpha.data-upstream.ch

---

**Describe the bug**
The frontend is actually sending the device_token as X-Access-Token and got the error response, but when I tried with the user's X-Access-Token, I got the same error response as well

{
    "errors": [
        "X-Access-Token is invalid."
    ]
}

**Screenshots** (click to enlarge)
![image](https://user-images.githubusercontent.com/28261161/52704356-4f757b80-2fbb-11e9-8d68-2ea6cd9c4efc.png)

**Comment by afitterling** [comment]
this is on design. need to send the first device token. startup the notebook!!

**Comment by afitterling** [comment]
actually it should be by design. the old one is definately working. the new one should also. use the first device token!

**Comment by afitterling** [comment]
or we wait untilni come back. could check the python notebooks?

**Comment by afitterling** [comment]
maybe you got this error because there is no log data. my devices work!

**Comment by afitterling** [comment]
i just checked https://alpha.data-upstream.ch/. it works! does your stream has data?

**Comment by afitterling** [comment]
need first device token and disable key rotation

**Comment by alvinvoo** [comment]
devices with key rotation 'on' will need to have their device access token ' consumed in order'  every time a request, i.e. POST or GET request is done on /log_data.json

The device access token has to be consumed from the first one on-wards. The index for the next available token is the one *right after* last_used_key_sequence (which starts at -1 for new device).

This is a non issue.
